CommandLineParser.dll: CommandLineOption.cs CommandLineBoolOption.cs CommandLineIntOption.cs CommandLineParser.cs CommandLineStringOption.cs ConfigurationException.cs ParsingException.cs
	dmcs -out:$@ CommandLineOption.cs CommandLineBoolOption.cs CommandLineIntOption.cs CommandLineParser.cs CommandLineStringOption.cs ConfigurationException.cs ParsingException.cs -target:library
